"""
CONFIG
"""

#tiles
TILE_SIZE = 16
SCALE = 4#tim c bon pour la taille ou pas??
DISPLAY_TILE_SIZE = TILE_SIZE * SCALE

#window
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60


def apply_resolution(width, height):
    global SCREEN_WIDTH, SCREEN_HEIGHT
    SCREEN_WIDTH = width
    SCREEN_HEIGHT = height

#player
PLAYER_MAX_SPEED = 100
PLAYER_ACCEL = 450
PLAYER_FRICTION = 450

PLAYER_SIZE_MULTIPLIER = 0.75
PLAYER_HITBOX_WIDTH = 18*PLAYER_SIZE_MULTIPLIER
PLAYER_HITBOX_HEIGHT = 18*PLAYER_SIZE_MULTIPLIER

#camera
CAMERA_LERP_SPEED = 10.0
CAMERA_ZOOM_LERP_SPEED = 6.0
CAMERA_MAX_ZOOM = 2.2
CAMERA_ROOM_MARGIN_TILES = 1 #tolerance

CAMERA_CORRIDOR_ZOOM = 2.95
CAMERA_SWAY_AMPLITUDE_PX = 2.5
CAMERA_SWAY_SPEED = 0.6
CAMERA_ZOOM_SWAY_AMPLITUDE = 0.015
CAMERA_ZOOM_SWAY_SPEED = 0.4

#sprite
PLAYER_SPRITE_WIDTH = 25
PLAYER_SPRITE_HEIGHT = 30
PLAYER_FOOT_ROW = 25

PLAYER_ANIMATION_FRAME_DURATION = {
    #spf
    "idle": 0.65,
    "walking": 0.12,
    "hurt": 0.08,
}

MAX_PLAYERS = 4

#settings
FONT_PATH = "assets/fonts/GrapeSoda.ttf"
FONT_SIZE_NORMAL = 20
FONT_SIZE_TITLE = 50
UI_SCALE = 4

GAME_TITLE = "Gembound"